### ISSUE TITLE
Modify ListAttendances view

### ISSUE THREAD

**Issue by BalintSedlak** [BalintSedlak/EvoNaplo#31]
- [x] Create the view on the picture
- [x] Add "View student profile" feature. New columns after student name or clickable student name
![image](https://user-images.githubusercontent.com/22743842/150313169-679ef7ab-c4e0-4c73-8584-66d171d5603a.png)

**Comment by marcibaumel** [comment]
![at](https://user-images.githubusercontent.com/11902504/168034146-0d947790-348e-47e8-b836-413b1bad97cd.png)

**Comment by marcibaumel** [comment]
"Add "View student profile" feature. New columns after student name or clickable student name" még nincs kész teljesen mivel a Student Profil nincsen kész ezért jelen pillanatban csak a console-ra írja ki a student összes adatát mikor rákattint a felhasználó bármelyik sorra.
