### ISSUE TITLE
Bulk edit on ListStudents view

### ISSUE THREAD

**Issue by BalintSedlak** [BalintSedlak/EvoNaplo#54]

**Comment by marcibaumel** [comment]
- [ ] Facebook csoport nem checkbox hanem leírás a profil alapján
- [ ] Ne lehessen rajta változtatni csak keresni
- [ ] Nyissa meg a diák profilját 
- [ ] Diák profiláján lehessen csak változtatni

**Comment by marcibaumel** [comment]
Ösztöndíj: Kap, jelentkezet, nem jelentkezett
